import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { LanguageProvider } from './providers/LanguageProvider';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { getTranslations } from './i18n';
import { headers } from 'next/headers';


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FlashAI",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) 
{
  // Get the locale from headers on the server-side
  // Get locale from cookies or default to 'en'
  const cookieStore = await cookies();
  const locale = cookieStore.get('NEXT_LOCALE')?.value || 'en';
  
  // Load messages for the current locale
  const messages = await getTranslations(locale);
  
  return (
    <html lang={locale} className={inter.className}>
      <body>
        <Providers>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Toaster />
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}